#!/usr/bin/env python

import os
import platform
import sys
import fnmatch
import re


root_dir = os.path.join(os.path.dirname(__file__), '..')
grapl_root = os.path.normpath(root_dir)
output_dir = os.path.join(os.path.abspath(grapl_root), 'out')

this_script_dir = os.path.dirname(__file__)
lib_root = os.path.normpath(this_script_dir)


sys.path.insert(0, os.path.join(grapl_root, 'build', 'gyp', 'pylib'))
sys.path.insert(0, os.path.join(grapl_root, 'build', 'pylib'))

try:
    import gyputil
except ImportError:
    print('Could not use gyputil :(')
    sys.exit(1)

include_headers = os.path.join(lib_root, 'grapl.h')

print lib_root
files = gyputil.find_files(lib_root, re.compile('.*\.h$'))
print files

with open(include_headers, 'w') as f:
    f.seek(0);
    f.write("""
/* THIS FILE WAS GENERATED BY lib/gen_include.py DO NOT EDIT MANUALLY
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#pragma once
""")
    for x in files:
        filename = x[4:]
        if filename != 'grapl.h' and "internal_" not in filename and "glxew.h" not in filename and "wglew.h" not in filename:
            print filename
            f.write("\n#include \"%s\"" % filename)
